ALTER TABLE roles
    ADD COLUMN IF NOT EXISTS sistema BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE permisos
    ADD COLUMN IF NOT EXISTS sistema BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE roles
SET sistema = TRUE
WHERE codigo IN ('ADMIN', 'ADMIN_EMPRESA', 'CAJERO', 'VENDEDOR', 'ALMACENERO');

UPDATE permisos
SET sistema = TRUE
WHERE codigo IN (
    'EMPRESAS_READ',
    'EMPRESAS_WRITE',
    'INVENTORY_READ',
    'INVENTORY_WRITE',
    'CLIENTES_READ',
    'CLIENTES_WRITE',
    'ROLES_READ',
    'ROLES_WRITE',
    'CAJA_READ',
    'CAJA_WRITE',
    'SUCURSALES_READ',
    'SUCURSALES_WRITE'
);
