package com.azurion.saascore.empresas.application.dto;

public record EmpresaResponse(
        Long id,
        String ruc,
        String razonSocial,
        String tipoDocumentoFiscal,
        String nombreComercial,
        String direccionFiscal,
        String distrito,
        String provincia,
        String departamento,
        String paisCodigo,
        String paisNombre,
        String correoPrincipal,
        String telefono,
        String celular,
        String sitioWeb,
        String facebook,
        String instagram,
        String representanteNombre,
        String representanteTipoDocumento,
        String representanteNumeroDocumento,
        String representanteCargo,
        String representanteCorreo,
        String representanteTelefono,
        String zonaHoraria,
        String idioma,
        String formatoFecha,
        String formatoHora,
        String monedaCodigo,
        String monedaSimbolo,
        String tenantId,
        String schemaName,
        String logoPanelUrl,
        boolean activo
) {
}
